## Logistic Regression using scikit-learn

In [3]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [4]:
X = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y = np.array([0, 0, 0, 1, 1, 1])

X.shape, y.shape

((6, 2), (6,))

In [5]:
model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [6]:
y_pred = model.predict(X)
y_pred

array([0, 0, 0, 1, 1, 1])

In [8]:
model.score(X, y_pred)

1.0

In [9]:
from sklearn.metrics import accuracy_score

accuracy_score(y, y_pred)

1.0

## Logistic Regression from Scratch

In [10]:
import numpy as np
from matplotlib import pyplot as plt

In [11]:
X = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y = np.array([0, 0, 0, 1, 1, 1])

X.shape, y.shape

((6, 2), (6,))

In [41]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs

    def sigmoid(self, z):
        return 1/(1+np.exp(- z))
    
    def compute_gradient(self, X, y):
        dw = np.zeros(self.n)
        db = 0.0

        for i in range(self.m):
            z = np.dot(X[i], self.w) + self.b
            f_x = self.sigmoid(z)
            err = f_x - y[i]
            for j in range(self.n):
                dw[j] += err*X[i, j]
            db += err
            
        dw = dw/self.m
        db = db/self.m

        return dw, db

    def compute_cost(self, X, y):
        cost = 0
        for i in range(self.m):
            z = np.dot(X[i], self.w) + self.b
            f_x = self.sigmoid(z)
            cost += -y[i]*np.log(f_x) - (1-y[i])*np.log(1-f_x)
        cost = cost/self.m
        return cost
    
    def fit(self, X, y):
        self.m, self.n =  X.shape

        self.w = np.zeros(self.n)
        self.b = 0

        for epoch in range(self.epochs):
            # Compute grdient
            dw, db = self.compute_gradient(X, y)
            
            # update the parameters using w, b, alpa and gradient
            self.w = self.w - self.learning_rate*dw
            self.b = self.b - self.learning_rate*db

            if epoch%100 == 0:
                print(f'Epoch {epoch}; cost: {self.compute_cost(X, y)}')

    def predict(self, X):
        z = np.dot(X, self.w) + self.b
        y_pred = self.sigmoid(z)
        return (y_pred >= 0.5)

In [42]:
model = LogisticRegression(learning_rate=0.001, epochs=1000)
model.fit(X, y)

Epoch 0; cost: 0.6930569518996433
Epoch 100; cost: 0.6849435841147226
Epoch 200; cost: 0.6783429390363866
Epoch 300; cost: 0.6729009474083217
Epoch 400; cost: 0.6683466322284212
Epoch 500; cost: 0.6644731349595011
Epoch 600; cost: 0.6611227117108094
Epoch 700; cost: 0.658175076919453
Epoch 800; cost: 0.6555384485834622
Epoch 900; cost: 0.6531427160248265


In [43]:
y

array([0, 0, 0, 1, 1, 1])

In [44]:
y_pred = model.predict(X)
y_pred

array([ True,  True,  True,  True,  True,  True])

In [14]:
X[0, 1]

1.5