In [1]:
import numpy as np
import time

In [5]:
a = np.zeros(4)
a, a.shape, a.dtype

(array([0., 0., 0., 0.]), (4,), dtype('float64'))

In [7]:
a = np.zeros((4, ))
a, a.shape, a.dtype

(array([0., 0., 0., 0.]), (4,), dtype('float64'))

In [8]:
a = np.random.random_sample(4)
a, a.shape, a.dtype

(array([0.17945711, 0.16915838, 0.417969  , 0.38126543]),
 (4,),
 dtype('float64'))

In [12]:
a = np.random.randint(0, 10, 4)
a, a.shape, a.dtype

(array([6, 6, 4, 7]), (4,), dtype('int32'))

In [17]:
a = np.arange(4)
a, a.shape, a.dtype

(array([0, 1, 2, 3]), (4,), dtype('int32'))

In [18]:
a = np.arange(4.)
a, a.shape, a.dtype

(array([0., 1., 2., 3.]), (4,), dtype('float64'))

In [21]:
a = np.random.rand(4)
a, a.shape, a.dtype

(array([0.28010131, 0.16597856, 0.8443869 , 0.83867049]),
 (4,),
 dtype('float64'))

In [22]:
a = np.random.rand(4, 3)
a, a.shape, a.dtype

(array([[0.38303824, 0.33563438, 0.65910231],
        [0.82734608, 0.95380177, 0.39143607],
        [0.80104688, 0.0882939 , 0.53485642],
        [0.89165938, 0.12811862, 0.89621547]]),
 (4, 3),
 dtype('float64'))

In [24]:
a = np.arange(10)
a, a.shape, a[2], a[-1]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,), 2, 9)

In [25]:
a = np.arange(10)
a, a.shape, a[2:7:2], a[3:], a[:3], a[:]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 (10,),
 array([2, 4, 6]),
 array([3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [27]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [28]:
b = -a
b

array([-1, -2, -3, -4])

In [29]:
b = np.sum(a)
b

10

In [30]:
b = np.mean(a)
b

2.5

In [31]:
b = a**2
b

array([ 1,  4,  9, 16])

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
a, b

(array([1, 2, 3, 4]), array([-1, -2,  3,  4]))

In [33]:
a + b

array([0, 0, 6, 8])

In [34]:
5*a

array([ 5, 10, 15, 20])

In [35]:
# Dot Product

def my_dot(a, b):
    m = a.shape[0]

    dot = 0
    for i in range(m):
        dot += a[i]*b[i]
    return dot

a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
np.dot(a, b), my_dot(a, b)

(24, 24)

In [36]:
a = np.zeros((2, 3))
a, a.shape

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 (2, 3))

In [37]:
a = np.zeros((2, 1))
a, a.shape

(array([[0.],
        [0.]]),
 (2, 1))

In [38]:
a = np.random.random_sample((2, 3))
a, a.shape

(array([[0.12708875, 0.83687492, 0.05037501],
        [0.81682492, 0.92281705, 0.52721785]]),
 (2, 3))

In [39]:
a = np.array([[5], [3], [2]])
a, a.shape

(array([[5],
        [3],
        [2]]),
 (3, 1))

In [40]:
a = np.arange(6).reshape(3, 2)
a, a.shape

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 (3, 2))

In [42]:
a[2, 0], a[2]

(4, array([4, 5]))

In [43]:
a = np.arange(20).reshape(-1, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
a[0,2:7:2]

array([2, 4, 6])